<nav aria-label="Page navigation" class="flex flex-col items-center justify-center md:flex-row-reverse md:justify-between mt-2">
    <ul class="pagination flex  space-x-2">

        <?php if ($paginator->hasPreviousPage()) : ?>
            <li class="page-item">
                <a class="page-link p-2 bg-emerald-300 hover:bg-emerald-400 text-black rounded" href="<?= route($paginator->getRouteName(), ['page' => $paginator->previousPage()]) ?>">Anterior</a>
            </li>
        <?php else : ?>
            <li class="page-item disabled">
                <a class="page-link p-2 bg-gray-300 text-gray-500 cursor-not-allowed">Anterior</a>
            </li>
        <?php endif; ?>

        <?php for ($page = 1; $page <= $paginator->totalOfPages(); $page++) : ?>
            <li class="page-item <?= $paginator->isPage($page) ? 'active' : '' ?>">
                <a class="page-link p-2 bg-emerald-300 hover:bg-emerald-400 text-black rounded" href="<?= route($paginator->getRouteName(), ['page' => $page]) ?>"><?= $page ?></a>
            </li>
        <?php endfor; ?>

        <?php if ($paginator->hasNextPage()) : ?>
            <li class="page-item">
                <a class="page-link p-2 bg-emerald-300 hover:bg-emerald-400 text-black rounded" href="<?= route($paginator->getRouteName(), ['page' => $paginator->nextPage()]) ?>">Próxima</a>
            </li>
        <?php else : ?>
            <li class="page-item disabled">
                <a class="page-link p-2 bg-gray-300 text-gray-500 cursor-not-allowed">Próxima</a>
            </li>
        <?php endif; ?>
    </ul>

    <div class="flex justify-end"><?= $paginator->entriesInfo() ?></div>

</nav>