<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Arrobacerta - Dashboard</title>
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
</head>

<body>
    <main class="container-fluid">

        <header class="w-full bg-gray-800 p-4 mb-4 h-[10%] flex flex-row items-center justify-between">

            <button data-drawer-target="separator-sidebar" onclick="openDrawer(event)" data-drawer-toggle="separator-sidebar" aria-controls="separator-sidebar" type="button" class="text-heading bg-transparent box-border border border-transparent hover:bg-neutral-secondary-medium text-gray-300 focus:ring-4 focus:ring-neutral-tertiary font-medium leading-5 rounded-base ms-3 text-sm p-2 focus:outline-none inline-flex sm:hidden">
                <svg class="w-6 h-6" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                    <path stroke="currentColor" stroke-linecap="round" stroke-width="2" d="M5 7h14M5 12h14M5 17h10" />
                </svg>
            </button>

            <div class="hidden md:block group relative bg-gray-700 text-gray-300 p-2 rounded-lg mr-4 xs:right-4 md:right-4 md:fixed lg:right-4 lg:fixed cursor-pointer">

                <?= $user->profile_photo_path ??
                    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-6">
                    <path fill-rule="evenodd" d="M7.5 6a4.5 4.5 0 1 1 9 0 4.5 4.5 0 0 1-9 0ZM3.751 20.105a8.25 8.25 0 0 1 16.498 0 .75.75 0 0 1-.437.695A18.683 18.683 0 0 1 12 22.5c-2.786 0-5.433-.608-7.812-1.7a.75.75 0 0 1-.437-.695Z" clip-rule="evenodd" />
                    </svg>' ?>

                <div class="hidden group-hover:block absolute right-0 top-full mt-2 w-60 bg-white rounded-md shadow-lg py-1 z-50 text-gray-800 p-2">
                    <div><span class="font-bold">Name:</span> <?= $user->name ?></div>
                    <div><span class="font-bold">Role:</span> <?= $user->role ?></div>
                    <div><span class="font-bold">E-mail:</span> <?= $user->email ?></div>
                </div>
            </div>

            <aside id="separator-sidebar" class="fixed top-0 left-0 z-30 w-64 h-screen bg-gray-800 transition-transform -translate-x-full sm:translate-x-0" aria-label="Sidebar">
                <div class="h-full px-3 py-4 overflow-y-auto bg-neutral-primary-soft border-e border-default">

                    <ul class="space-y-2 font-medium">
                        <h1>
                            <a href="/dashboard" class=" border rounded-lg flex flex-col justify-center items-center text-2xl text-gray-300">
                                Arrobacerta
                                <span class="font-bold"><?= $title ?></span>
                            </a>
                        </h1>

                        <li class="mt-3 hover:bg-gray-700">
                            <a href="#" class="flex items-center px-2 text-gray-400 py-1.5 text-body rounded-base hover:bg-neutral-tertiary hover:text-fg-brand group">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-8">
                                    <path fillRule="evenodd" d="M18.685 19.097A9.723 9.723 0 0 0 21.75 12c0-5.385-4.365-9.75-9.75-9.75S2.25 6.615 2.25 12a9.723 9.723 0 0 0 3.065 7.097A9.716 9.716 0 0 0 12 21.75a9.716 9.716 0 0 0 6.685-2.653Zm-12.54-1.285A7.486 7.486 0 0 1 12 15a7.486 7.486 0 0 1 5.855 2.812A8.224 8.224 0 0 1 12 20.25a8.224 8.224 0 0 1-5.855-2.438ZM15.75 9a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0Z" clipRule="evenodd" />
                                </svg>
                                <span class="ms-3">User panel</span>
                            </a>
                        </li>

                        <li class="bottom-0 fixed w- mb-4 hover:underline hover:text-red-100">
                            <a href="logout" class="flex items-center px-2 text-red-500 py-1.5 text-body rounded-base hover:bg-neutral-tertiary hover:text-fg-brand group">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6">
                                    <path fillRule="evenodd" d="M7.5 3.75A1.5 1.5 0 0 0 6 5.25v13.5a1.5 1.5 0 0 0 1.5 1.5h6a1.5 1.5 0 0 0 1.5-1.5V15a.75.75 0 0 1 1.5 0v3.75a3 3 0 0 1-3 3h-6a3 3 0 0 1-3-3V5.25a3 3 0 0 1 3-3h6a3 3 0 0 1 3 3V9A.75.75 0 0 1 15 9V5.25a1.5 1.5 0 0 0-1.5-1.5h-6Zm10.72 4.72a.75.75 0 0 1 1.06 0l3 3a.75.75 0 0 1 0 1.06l-3 3a.75.75 0 1 1-1.06-1.06l1.72-1.72H9a.75.75 0 0 1 0-1.5h10.94l-1.72-1.72a.75.75 0 0 1 0-1.06Z" clipRule="evenodd" />
                                </svg>
                                <span class="ms-3">LogOut</span>
                            </a>
                        </li>
                    </ul>

                </div>
            </aside>
        </header>

        <?php require $view ?>

    </main>

    <script>
        function openDrawer(event) {
            event?.stopPropagation();
            const drawer = document.getElementById('separator-sidebar');
            drawer.classList.toggle('-translate-x-full');
        }

        document.addEventListener('click', function(event) {
            const drawer = document.getElementById('separator-sidebar');
            const toggleButton = document.querySelector('[data-drawer-target="separator-sidebar"]');

            if (!drawer.classList.contains('-translate-x-full') && !drawer.contains(event.target) && event.target !== toggleButton) {
                drawer.classList.add('-translate-x-full');
            }
        });
    </script>
</body>

</html>