<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Arrobacerta - Dashboard</title>
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/all.min.css"/>
</head>

<body>
    <main class="container-fluid sm:ml-64">

        <header class="w-full bg-gray-800 p-4 mb-4 h-[10%] flex flex-row items-center justify-between">

            <button data-drawer-target="separator-sidebar" onclick="openDrawer(event)" data-drawer-toggle="separator-sidebar" aria-controls="separator-sidebar" type="button" class="text-heading bg-transparent box-border border border-transparent hover:bg-neutral-secondary-medium text-gray-300 focus:ring-4 focus:ring-neutral-tertiary font-medium leading-5 rounded-base ms-3 text-sm p-2 focus:outline-none inline-flex sm:hidden">
                <svg class="w-6 h-6" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                    <path stroke="currentColor" stroke-linecap="round" stroke-width="2" d="M5 7h14M5 12h14M5 17h10" />
                </svg>
            </button>

            <div class="hidden md:block group relative bg-gray-700 text-gray-300 p-2 rounded-lg mr-4 xs:right-4 md:right-4 md:fixed lg:right-4 lg:fixed cursor-pointer">

                <?= $user->profile_photo_path ??
                    '<i class="fa-solid fa-user font-bold"></i>' ?>

                <div class="hidden group-hover:block absolute right-0 top-full mt-2 w-60 bg-white rounded-md shadow-lg py-1 z-50 text-gray-800 p-2">
                    <div><span class="font-bold">Name:</span> <?= $user->name ?></div>
                    <div><span class="font-bold">Role:</span> <?= $user->role ?></div>
                    <div><span class="font-bold">E-mail:</span> <?= $user->email ?></div>
                </div>
            </div>

            <aside id="separator-sidebar" class="fixed top-0 left-0 z-30 w-64 h-screen bg-gray-800 transition-transform -translate-x-full sm:translate-x-0" aria-label="Sidebar">
                <div class="h-full px-3 py-4 overflow-y-auto bg-neutral-primary-soft border-e border-default">

                    <ul class="space-y-2 font-medium">
                        <h1>
                            <a href="/dashboard" class=" border rounded-lg flex flex-col justify-center items-center text-2xl text-gray-300">
                                Arrobacerta
                                <span class="font-bold text-amber-500"><?= $title ?></span>
                            </a>
                        </h1>

                        <li class="mt-3 hover:bg-gray-700">
                            <a href="#" class="flex items-center px-2 text-gray-400 py-1.5 text-body rounded-base hover:bg-neutral-tertiary hover:text-fg-brand group">
                                <i class="fa-solid fa-user font-bold"></i>
                                <span class="ms-3">User panel</span>
                            </a>
                        </li>

                        <li class="mt-3 hover:bg-gray-700">
                            <a href="/cattle" class="flex items-center px-2 text-gray-400 py-1.5 text-body rounded-base hover:bg-neutral-tertiary hover:text-fg-brand group">
                                <i class="fa-solid fa-cow font-bold"></i>
                                <span class="ms-3">Cattle</span>
                            </a>
                        </li>

                        <li class="bottom-0 fixed w- mb-4 hover:underline hover:text-red-100">
                            <a href="logout" class="flex items-center px-2 text-red-500 py-1.5 text-body rounded-base hover:bg-neutral-tertiary hover:text-fg-brand group">
                                <i class="fa-solid fa-arrow-right-from-bracket font-bold"></i>
                                <span class="ms-3">LogOut</span>
                            </a>
                        </li>
                    </ul>

                </div>
            </aside>
        </header>

        <?php require $view ?>

    </main>

    <script>
        function openDrawer(event) {
            event?.stopPropagation();
            const drawer = document.getElementById('separator-sidebar');
            drawer.classList.toggle('-translate-x-full');
        }

        document.addEventListener('click', function(event) {
            const drawer = document.getElementById('separator-sidebar');
            const toggleButton = document.querySelector('[data-drawer-target="separator-sidebar"]');

            if (!drawer.classList.contains('-translate-x-full') && !drawer.contains(event.target) && event.target !== toggleButton) {
                drawer.classList.add('-translate-x-full');
            }
        });
    </script>
</body>

</html>